version: "3.7"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
